spring:
  application:
    name: websdk
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jimmer_demo
    username: root
    password: root
# 程序启动端口
server:
  port: 1178

# 这里不懂不要动
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: ERROR

app:
  # 游戏服列表 最多配置五个区域 [cn tw jp kr global]
  gateServerMap:
    cn:
      # 如果使用 nebula，agent-zone-xx 要改成 agent-zone-1
      gateServerAddress: "http://127.0.0.1/agent-zone-cn"
      reportServerAddress: "http://127.0.0.1/report"
      bigVersion: 1.4 # 大版本号
      dataVersion: 77 # 小版本号
      statusCode: 1
      zoneId: 1
    tw:
      gateServerAddress: "http://127.0.0.1/agent-zone-tw"
      reportServerAddress: "http://127.0.0.1/report"
      bigVersion: 1.4
      dataVersion: 76
      statusCode: 1
      zoneId: 1
# 以下两个是配合 nebula 游戏服的设置，没有这个需求的话就改成空字符串
  nebulaCommandServer: "http://127.0.0.1:80/api/command"
  nebulaCommandServerAuthToken: "HJHASDPIIQWEASDHHAN"