spring:
  application:
    name: websdk
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jimmer_demo
    username: root
    password: root

server:
  port: 1178

jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: ERROR

app:
  gateServerMap:
    cn:
      ip: 127.0.0.1
      port: 80
      uri: cn
      useSSL: false
      ossHost: "https://nova-static.yostar.cn"
      bigVersion: 1.4
      dataVersion: 76
    tw:
      ip: 127.0.0.1
      port: 80
      useSSL: false
      uri: tw
      ossHost: "https://nova-static.stargazer-games.com"
      bigVersion: 1.4
      dataVersion: 76
  nebulaCommandServer: "http://127.0.0.1:80/api/command"
  nebulaCommandServerAuthToken: "HJHASDPIIQWEASDHHAN"