spring:
  application:
    name: websdk
#  æ•°æ®åº“é…ç½®
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jimmer_demo
    username: root
    password: root
# ç¨‹åºå¯åŠ¨ç«¯å£
server:
  port: 1178

# è¿™é‡Œä¸æ‡‚ä¸è¦åŠ¨
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: ERROR

app:
#  æ¸¸æˆæœåˆ—è¡¨ æœ€å¤šé…ç½®äº”ä¸ªåŒºåŸŸ [cn tw jp kr global]
  gateServerMap:
    cn:
      ip: 127.0.0.1
      port: 80
      uri: cn # æ¸¸æˆæœé™„åŠ è·¯å¾„ ä¸çŸ¥é“æ€ä¹ˆå¡«å°±å¡«1
      useSSL: false
      # yostar DMCAğŸ˜­
      ossHost: "https://nova-static.DMCAğŸ˜­.cn" # å¤§æ–‡ä»¶èµ„æºå­˜æ”¾åœ°å€ ç”¨äºçƒ­æ›´æ–°
      bigVersion: 1.4 # å¤§ç‰ˆæœ¬å·
      dataVersion: 76 # å°ç‰ˆæœ¬å·
    tw:
      ip: 127.0.0.1
      port: 80
      useSSL: false
      uri: tw
      # stargazer-games DMCAğŸ˜­
      ossHost: "https://nova-static.DMCAğŸ˜­.com"
      bigVersion: 1.4
      dataVersion: 76
# ä»¥ä¸‹ä¸¤ä¸ªæ˜¯é…åˆ nebula æ¸¸æˆæœçš„è®¾ç½®ï¼Œæ²¡æœ‰è¿™ä¸ªéœ€æ±‚çš„è¯å°±æ”¹æˆç©ºå­—ç¬¦ä¸²
  nebulaCommandServer: "http://127.0.0.1:80/api/command"
  nebulaCommandServerAuthToken: "HJHASDPIIQWEASDHHAN"